# Definition of QA pipeline at SonarSource
#
# Possible values for SLAVE: "performance" (for perf tests) and "linux" (for linux machines connected to DB services)

SQ_VERSION: 
  - DEV
  - LTS

JENKINS_VERSION:
  - 1.651.3
  - 2.7.4

SLAVE:
  - linux

exclude:
  - SQ_VERSION: LTS
    JENKINS_VERSION: 2.7.4

  - SQ_VERSION: DEV
    JENKINS_VERSION: 1.651.3
  
